export {default as MainPage} from './MainPage'
export {default as UserPage} from './UserPage'
export {default as EachPostPage} from './EachPostPage'
export {default as NotFound} from './NotFound'
export {default as WritingPage} from './WritingPage'
export {default as RegisterPage} from './RegisterPage'
